### PR TITLE
Add validate parameter, Add unit test test for lng > 180.

### PR DESCRIPTION
**Pull request by guidorice**
This pull request :

* adds the validate parameter and code changes from the gist in:
https://github.com/guidorice/antimeridian_splitter/issues/1

* It also adds the validate parameter to all the unit tests.

* unit tests are moved to directory outside the package (recommended by pytest)

### CODE REVIEW

**Comment by guidorice** [comment]
@PawaritL hi, I added in your recent gist changes, but the validate parameter is not working with your original example polygon, which actually results in `check_crossing()` being called with values `lon1: -179.0 lon2: 181.01`.

See the pytest output here:
https://github.com/guidorice/antimeridian_splitter/pull/2/checks?check_run_id=3202324114#step:6:98

I think the validation check might need to be refactored or moved into a different function (it needs to check the original longitude representation, not the value sent to check_crossing?)

note: if you want to run pytest locally, you have to use the cmd `python -m pytest` because of the tests being at the root directory.

**Comment by k-rns** [comment]
Did this issue get resolved? I was trying to use this antimeridian splitter, but the check crossing keeps on failing.

**Comment by guidorice** [comment]
@k-rns hello. Nope this PR, and the related #1 is not fixed. 

If you run the latest code in the `main` branch, the package should work, but definitely consider it to be alpha/experimental. There are  also some edge cases not working, like the current issue.

I am going to close out this PR as there are now a few conflicts with `main`, and probably a different approach will be needed to solve this issue.

**Comment by k-rns** [comment]
Thanks @guidorice! It looked so promising diving into it.

**Pull request closed without merging**
